#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
sync-design-questions.py -- render pdoom1's open design questions to /design-questions/.

WHY THIS EXISTS
---------------
pdoom1 holds 38 numbered Design Questions: the things about the game that are
genuinely undecided, with the evidence for and against. They are the most
text-rich, most honest material in the estate and almost nobody has seen them.
Pip, 2026-08-11: "anyone even slightly interested in reading would get a lot out
of a slightly cleaned up presentation of them."

This is the CHEAPEST FIRST STEP: the index only. Number, title, status and ONE
derived line each. Full bodies follow for the questions that earn it.

IDENTITY COMES FROM pdoom1'S OWN GENERATED INDEX, NOT FROM PARSING PROSE
------------------------------------------------------------------------
`docs/game-design/DQ_INDEX.md` is generated by pdoom1's own
`scripts/generate_dq_index.py`, and a pre-commit check there fails any commit that
changes the backlog without regenerating it. So the index is authoritative for
number, title and status, and it carries the BACKLOG LINE NUMBER for each entry.

That matters, because the first attempt at this parsed the backlog directly and
got it wrong twice in ways worth recording:

  * it dropped DQ-21, DQ-27 and DQ-31 -- every entry whose TITLE contains an
    em-dash, which is also the character separating title from status. Composing
    identity from a delimiter that appears inside the content.
  * it ran one entry's body into the next, so a CLEAN question (DQ-25) was
    flagged for a marker belonging to the note after it.

Using the index's line numbers as anchors removes both. **38 rows in, 38 rows out,
or this script refuses.** It never silently drops one.

MARKERS: CLASSIFY, DO NOT BLANKET-SCRUB
---------------------------------------
sync-design-notes.py refuses to publish a body carrying an internal process
marker, which is right for ADRs. Here it would be wrong, because some markers are
exactly what a reader wants:

  CAVEAT   "post-merge todo: regenerate the balance docs" means THESE NUMBERS
           HAVE A CAVEAT. Published, as a caveat. Hiding it would leave a figure
           looking more settled than it is.
  REFUSE   anything else, or anything unrecognised. An unclassifiable marker is
           not published and the row renders title-and-status only.

The default is REFUSE. A new marker shape this script has not seen is treated as
internal, never as safe.

NO RUNTIME FETCH
----------------
Static HTML generated here, like sync-design-notes.py. Works with JS off, adds no
new fetch target to declare in test-escaping.js, and every interpolation is
escaped at generation time.

RUN
    python scripts/sync/sync-design-questions.py --game-repo ../pdoom1
    python scripts/sync/sync-design-questions.py --check     # write nothing
"""

import argparse
import html
import io
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        try:
            if _s is sys.stdout:
                sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
        except Exception:
            pass

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "public" / "design-questions" / "index.html"

INDEX_ROW = re.compile(
    r"^\|\s*(?P<key>DQ-\d+(?:\s*ext)?)\s*\|\s*(?P<title>[^|]+?)\s*\|"
    r"\s*(?P<status>[^|]+?)\s*\|\s*(?P<line>\d+)\s*\|")

# Markers that are a READER-FACING CAVEAT, with the sentence to render instead.
CAVEAT_MARKERS = [
    (re.compile(r"post-merge todo", re.I),
     "Balance figures here predate a later migration and are pending regeneration."),
    (re.compile(r"awaiting (?:Pip )?review", re.I),
     "Awaiting review; treat as proposed rather than settled."),
    (re.compile(r"re-confirm numbers", re.I),
     "Numbers to be re-confirmed against the current model."),
]
# Anything matching this and NOT classified above is internal. Default: refuse.
INTERNAL = re.compile(r"\b(TODO|FIXME|WIP|do not ship|internal only|@claude|DRAFT ONLY)\b",
                      re.I)


def esc(s):
    """& < > \" and ' -- the apostrophe too, because this page has no reviewer
    guaranteeing every attribute stays double-quoted."""
    return html.escape("" if s is None else str(s), quote=True)


def one_line(body):
    """A summary DERIVED from the first sentence. Never invented."""
    t = re.sub(r"\s+", " ", body).strip()
    # ORDER MATTERS and getting it wrong is silent: the body begins
    #   "- **DQ-7 · Title — STATUS** *(refs)* — the actual sentence"
    # so the list bullet must go BEFORE the bold header, or the header anchor
    # never matches and the whole heading ends up in the summary looking fine.
    t = re.sub(r"^[-*+]\s+", "", t)
    t = re.sub(r"^\*\*DQ-\d+(?:\s*ext)?\s*[·.].*?\*\*\s*", "", t)
    t = re.sub(r"^\*\([^)]*\)\*\s*", "", t)
    t = re.sub(r"^[-—–]\s*", "", t)
    # The "ext" entries are nested sub-bullets, so once the header is removed the
    # remaining text can still open with its own list marker. Strip once more --
    # after the header, not instead of it.
    t = re.sub(r"^[-*+]\s+", "", t)
    t = re.sub(r"\*\*(.+?)\*\*", r"\1", t)
    t = re.sub(r"`([^`]*)`", r"\1", t)
    t = t.replace("*", "")
    m = re.search(r"(.+?[.?!])(\s|$)", t)
    s = (m.group(1) if m else t).strip()
    return s


def classify(body):
    """Returns (caveats, refused). Default is refuse."""
    caveats = []
    for pat, sentence in CAVEAT_MARKERS:
        if pat.search(body):
            caveats.append(sentence)
    residual = INTERNAL.sub("", body) if caveats else body
    refused = bool(INTERNAL.search(residual)) if caveats else bool(INTERNAL.search(body))
    return caveats, refused


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--game-repo", default=os.environ.get("PDOOM1_REPO", "../pdoom1"))
    ap.add_argument("--check", action="store_true", help="verify only, write nothing")
    args = ap.parse_args()

    game = Path(args.game_repo).resolve()
    idx_p = game / "docs" / "game-design" / "DQ_INDEX.md"
    bak_p = game / "docs" / "game-design" / "WORKSHOP_2_BACKLOG.md"
    if not idx_p.exists() or not bak_p.exists():
        print("REFUSING: no pdoom1 checkout at %s" % game)
        print("  This mirrors a document set the website does not own. Point it at a")
        print("  local checkout with --game-repo or $PDOOM1_REPO.")
        return 2

    rows = []
    for line in idx_p.read_text(encoding="utf-8").splitlines():
        m = INDEX_ROW.match(line.strip())
        if m and m.group("key").upper().startswith("DQ-"):
            rows.append({"key": re.sub(r"\s+", " ", m.group("key")).strip(),
                         "title": m.group("title").strip(),
                         "status": m.group("status").strip(),
                         "line": int(m.group("line"))})
    if not rows:
        print("REFUSING: parsed 0 rows from DQ_INDEX.md.")
        return 2

    backlog = bak_p.read_text(encoding="utf-8").splitlines()
    starts = sorted({r["line"] for r in rows})
    # An entry ends at the NEXT TOP-LEVEL BULLET, not at the next DQ. The backlog
    # interleaves non-DQ bullets between questions ("Ledger failure states TODO"),
    # and ending at the next DQ swallows them -- which flagged two CLEAN questions
    # for markers belonging to somebody else's bullet. Third instance of one class:
    # a boundary inferred from a delimiter that does not reliably mark one.
    for r in rows:
        s = r["line"] - 1
        e = len(backlog)
        for j in range(s + 1, len(backlog)):
            if backlog[j].startswith("- **") or backlog[j].startswith("#"):
                e = j
                break
        body = "\n".join(backlog[s:e])
        r["summary"] = one_line(body)
        r["caveats"], r["refused"] = classify(body)

    missing = [r["key"] for r in rows if not r["summary"]]
    refused = [r["key"] for r in rows if r["refused"]]

    print("Design questions -- mirrored from pdoom1")
    print("=" * 70)
    print("  index rows        %d" % len(rows))
    print("  with a summary    %d" % len([r for r in rows if r["summary"]]))
    print("  carrying a caveat %d %s" % (len([r for r in rows if r["caveats"]]),
                                         [r["key"] for r in rows if r["caveats"]]))
    print("  body REFUSED      %d %s" % (len(refused), refused))
    if missing:
        print()
        print("  REFUSING TO WRITE: %d row(s) have no derivable summary: %s"
              % (len(missing), ", ".join(missing)))
        print("  A row published without its line would be an undercount wearing a")
        print("  complete-looking table.")
        return 1

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    body_rows = []
    for r in rows:
        cav = ""
        if r["caveats"]:
            cav = ('<div class="cav">' +
                   " ".join(esc(c) for c in r["caveats"]) + "</div>")
        summary = ("<em>Full text withheld: this entry carries an internal note this "
                   "mirror does not publish.</em>" if r["refused"]
                   else esc(r["summary"]))
        body_rows.append(
            '<tr><td class="k">%s</td><td class="t">%s%s</td>'
            '<td class="s"><span class="pill">%s</span></td></tr>'
            % (esc(r["key"]), summary and ('<b>%s</b><br><span class="d">%s</span>'
                                           % (esc(r["title"]), summary)) or esc(r["title"]),
               cav, esc(r["status"])))

    page = """<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Design questions -- p(Doom)1</title>
<meta name="description" content="The %d design questions p(Doom)1 has not settled yet, with their current status.">
<link rel="stylesheet" href="/css/site.css">
<style>
:root{--bg-primary:#12100F;--bg-secondary:#1C1917;--bg-tertiary:#262220;
--text-primary:#E9F2F2;--text-secondary:#CFC7BB;--text-muted:#A79E92;
--accent-primary:#F6A800;--accent-secondary:#2FD4C2;--accent-danger:#E2524A;
--border:#3A342E;--border-strong:#574E44;--success:#4FB37A;--warning:#E9752E}
body{background:var(--bg-primary);color:var(--text-primary);
font-family:'Courier New',monospace;line-height:1.55;margin:0}
main{max-width:60rem;margin:0 auto;padding:2rem 1.25rem 4rem}
h1{color:var(--accent-primary);margin:.2rem 0 .4rem;font-size:1.7rem}
.lede{color:var(--text-secondary);max-width:46rem}
.note{background:var(--bg-secondary);border-left:3px solid var(--accent-secondary);
padding:.75rem 1rem;margin:1.5rem 0;color:var(--text-secondary)}
table{width:100%%;border-collapse:collapse;margin-top:1.5rem}
th{text-align:left;color:var(--text-muted);font-weight:normal;
border-bottom:1px solid var(--border-strong);padding:.5rem .6rem;font-size:.85rem}
td{border-bottom:1px solid var(--border);padding:.7rem .6rem;vertical-align:top}
.k{color:var(--accent-secondary);white-space:nowrap;font-size:.9rem}
.d{color:var(--text-secondary);font-size:.92rem}
.cav{color:var(--warning);font-size:.85rem;margin-top:.35rem}
.pill{border:1px solid var(--border-strong);border-radius:1rem;
padding:.1rem .55rem;font-size:.78rem;color:var(--text-muted);white-space:nowrap}
footer{color:var(--text-muted);font-size:.85rem;margin-top:2.5rem;
border-top:1px solid var(--border);padding-top:1rem}
a{color:var(--accent-primary)}
</style></head><body>
<header></header>
<main>
<h1>Design questions</h1>
<p class="lede">These are the things about p(Doom)1 that are <strong>not settled</strong>.
Not a roadmap and not a promise &mdash; a list of questions the game is genuinely
holding open, with where each currently stands.</p>

<div class="note">Each line below is a one-sentence summary derived from the design
backlog. <strong>The full text of each is being prepared.</strong> Nothing here is a
commitment that a question will be answered a particular way, or at all &mdash; an open
question is exactly that.</div>

<table>
<thead><tr><th>Ref</th><th>Question</th><th>Status</th></tr></thead>
<tbody>
%s
</tbody></table>

<footer>
Mirrored from the p(Doom)1 design backlog on %s. Identity and status come from the
game repository's own generated index, so this table cannot disagree with it about
which questions exist. Where a figure has a caveat, the caveat is shown rather than
hidden.
</footer>
</main>
<script src="/assets/js/navigation.js"></script>
</body></html>
""" % (len(rows), "\n".join(body_rows), esc(stamp))

    if args.check:
        if not OUT.exists():
            print("  --check: page not written yet")
            return 1
        cur = OUT.read_text(encoding="utf-8")
        same = re.sub(r"on \d{4}-\d{2}-\d{2}", "", cur) == re.sub(r"on \d{4}-\d{2}-\d{2}", "", page)
        print("  --check: %s" % ("in step" if same else "STALE -- regenerate"))
        return 0 if same else 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(page, encoding="utf-8")
    print()
    print("  wrote %s (%d rows, %d bytes)" % (OUT.relative_to(ROOT), len(rows), len(page)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
