#!/usr/bin/env python
"""Inline scripts/review-print.css into every print-first memo in public/_review/.

WHY A SCRIPT AND NOT A <link>
    public/_review/ is gitignored (it sits inside the deploy root), so the memos
    themselves can never be the tracked source of their own styling. The tracked
    source is scripts/review-print.css; this script copies it into each memo
    between marker comments so the memo stays a single self-contained file.

WHY IT IS NOT WIRED TO CI
    CI has no public/_review/ -- the directory is ignored and exists only on
    Pip's box. A workflow running this would find zero memos and pass vacuously,
    which CLAUDE.md's severity model calls out by name ("a guard seen only in its
    passing state has not been shown to work"). So it stays a local tool, and it
    prints SKIP -- loudly, not silently -- when there is nothing to act on.

WHAT COUNTS AS A PRINT-FIRST MEMO
    A .html file in public/_review/ whose <style> contains an `@page` rule.
    That excludes index.html and content.html, which are dark-theme interactive
    screen pages and are not meant to reach a printer.

USAGE
    python scripts/apply-review-print-css.py            # write
    python scripts/apply-review-print-css.py --check    # exit 1 if any is stale
"""
import re
import sys
from pathlib import Path

# Windows console is cp1252; a non-ASCII print dies on the FIRST print, before
# any work happens. See CLAUDE.md "Environment / tooling".
for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

BEGIN = "/* BEGIN review-print.css -- generated by scripts/apply-review-print-css.py; edit that .css, not this */"
END = "/* END review-print.css */"

REPO = Path(__file__).resolve().parent.parent
CSS_SRC = REPO / "scripts" / "review-print.css"
REVIEW_DIR = REPO / "public" / "_review"

BLOCK_RE = re.compile(
    re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
    re.DOTALL,
)


def payload() -> str:
    """The exact text that must sit between the markers, markers included."""
    css = CSS_SRC.read_text(encoding="utf-8").rstrip("\n")
    return BEGIN + "\n" + css + "\n" + END + "\n"


def is_print_first(html: str) -> bool:
    # An @page rule is the discriminator. Ignore one that only appears inside our
    # own injected block, so a half-applied file is still classified correctly.
    stripped = BLOCK_RE.sub("", html)
    return re.search(r"@page\s*\{", stripped) is not None


def rewrite(html: str, block: str) -> str:
    """Return html with the block present exactly once, last in the first <style>."""
    html = BLOCK_RE.sub("", html)

    # Insert before the </style> that closes the style element carrying @page, so
    # our rules land last and win the cascade against the memo's own @page.
    for m in re.finditer(r"<style[^>]*>(.*?)</style>", html, re.DOTALL | re.IGNORECASE):
        if re.search(r"@page\s*\{", m.group(1)):
            close = m.end() - len("</style>")
            head = html[:close]
            if not head.endswith("\n"):
                head += "\n"
            return head + block + html[close:]
    raise SystemExit("no <style> block containing @page -- refusing to guess where to inject")


def main() -> int:
    check = "--check" in sys.argv[1:]

    if not CSS_SRC.exists():
        print(f"FAIL: missing {CSS_SRC}")
        return 2
    if not REVIEW_DIR.is_dir():
        # Not an error: the directory is gitignored, so a fresh clone, a worktree
        # or a CI runner legitimately has none. Say so rather than exiting silent.
        print(f"SKIP: no {REVIEW_DIR} on this checkout (gitignored; exists only on Pip's box)")
        return 0

    block = payload()
    memos, skipped, stale, wrote = [], [], [], []

    for path in sorted(REVIEW_DIR.glob("*.html")):
        html = path.read_text(encoding="utf-8")
        if not is_print_first(html):
            skipped.append(path.name)
            continue
        memos.append(path.name)
        if block in html:
            continue
        stale.append(path.name)
        if not check:
            path.write_text(rewrite(html, block), encoding="utf-8")
            wrote.append(path.name)

    if not memos:
        print(f"SKIP: {REVIEW_DIR} holds no print-first memo (none carries an @page rule)")
        return 0

    for name in skipped:
        print(f"  skip   {name}  (screen page, no @page rule)")
    for name in memos:
        mark = "STALE" if name in stale else "ok"
        print(f"  {mark:5s}  {name}")

    if check:
        if stale:
            print(f"\nFAIL: {len(stale)} of {len(memos)} memo(s) lack the current "
                  f"review-print.css block. Run: python scripts/apply-review-print-css.py")
            return 1
        print(f"\nOK: all {len(memos)} print-first memo(s) carry the current block.")
        return 0

    print(f"\nwrote {len(wrote)} of {len(memos)} print-first memo(s); "
          f"{len(memos) - len(wrote)} already current.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
