name: Deploy to DreamHost (manual)

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run rsync with --dry-run to preview changes"
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check required secrets
        run: |
          for v in DH_HOST DH_USER DH_PATH DH_SSH_KEY; do
            if [ -z "${!v}" ]; then echo "Missing secret: $v"; MISSING=1; fi;
          done
          if [ "${MISSING}" = "1" ]; then exit 1; fi
        env:
          DH_HOST: ${{ secrets.DH_HOST }}
          DH_USER: ${{ secrets.DH_USER }}
          DH_PATH: ${{ secrets.DH_PATH }}
          DH_SSH_KEY: ${{ secrets.DH_SSH_KEY }}
          DH_PORT: ${{ secrets.DH_PORT }}

      - uses: actions/checkout@v4

      - name: Setup SSH
        env:
          DH_SSH_KEY: ${{ secrets.DH_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DH_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          printf "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Ensure remote path exists
        env:
          DH_HOST: ${{ secrets.DH_HOST }}
          DH_USER: ${{ secrets.DH_USER }}
          DH_PATH: ${{ secrets.DH_PATH }}
          DH_PORT: ${{ secrets.DH_PORT }}
        run: |
          PORT=${DH_PORT:-22}
          ssh -p "$PORT" "${DH_USER}@${DH_HOST}" "mkdir -p '${DH_PATH}'"

      - name: Deploy public/ via rsync
        env:
          DH_HOST: ${{ secrets.DH_HOST }}
          DH_USER: ${{ secrets.DH_USER }}
          DH_PATH: ${{ secrets.DH_PATH }}
          DH_PORT: ${{ secrets.DH_PORT }}
        run: |
          set -euo pipefail
          RSYNC_FLAGS="-avz --delete"
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            RSYNC_FLAGS="$RSYNC_FLAGS --dry-run"
          fi
          PORT=${DH_PORT:-22}
          rsync $RSYNC_FLAGS -e "ssh -p $PORT" public/ "${DH_USER}@${DH_HOST}:${DH_PATH}/"
