# Placeholder deploy (manual only)
name: deploy

on:
  workflow_dispatch:
    inputs:
      note:
        description: Manual run only
        required: false

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Add your deploy steps here'