name: Sync Airtable to JSON

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run sync script
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_BLOG_TABLE: ${{ secrets.AIRTABLE_BLOG_TABLE }}
          AIRTABLE_CHANGELOG_TABLE: ${{ secrets.AIRTABLE_CHANGELOG_TABLE }}
        run: |
          python scripts/sync_airtable.py
      - name: Commit changes
        run: |
          if git diff --quiet public/data; then
            echo "No changes"
          else
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add public/data/*.json
            git commit -m "chore(data): sync Airtable to JSON"
            git push
          fi
